# Generated by Django 4.2.3 on 2023-07-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='emoji',
            field=models.CharField(max_length=10),
        ),
    ]
