# Generated by Django 4.2.3 on 2023-11-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0002_alter_categoria_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
