# Generated by Django 4.2.3 on 2023-11-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0004_evento_stripe_price_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
