# Generated by Django 4.2.3 on 2023-10-24 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RA', 'Richiesta di Amicizia'), ('AE', 'Aggiornamento Evento')], default='RA', max_length=2)),
                ('testo', models.TextField()),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('letta', models.BooleanField(default=False)),
                ('mittente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifiche_inviate', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiche', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_creazione'],
            },
        ),
    ]
