# Generated by Django 4.2.3 on 2023-10-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0002_notifica'),
    ]

    operations = [
        migrations.AddField(
            model_name='utentebase',
            name='amici',
            field=models.ManyToManyField(blank=True, to='utenti.utentebase'),
        ),
    ]
