# Generated by Django 4.2.3 on 2023-11-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utenti', '0003_utentebase_amici'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizzatore',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
