# Generated by Django 4.2.3 on 2023-11-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0005_alter_evento_stripe_price_id'),
        ('utenti', '0004_organizzatore_stripe_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizzatore',
            name='eventi',
            field=models.ManyToManyField(blank=True, null=True, to='eventi.evento'),
        ),
    ]
