# Generated by Django 4.2.3 on 2023-11-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventi', '0005_alter_evento_stripe_price_id'),
        ('utenti', '0005_alter_organizzatore_eventi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizzatore',
            name='eventi',
            field=models.ManyToManyField(blank=True, to='eventi.evento'),
        ),
    ]
