"""
Django settings for movidamo project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from base64 import encode
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t88$g&ymtn5#6kc-o*kqkqzol($bl2u8@b--5iu+adc2kv^p^7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['movidamo.azurewebsites.net','127.0.0.1','192.168.1.156', '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',
    "sslserver",
    'eventi',
    'utenti',
    'mappa',
    'mathfilters',
    'raccomandazioni',
    'django_extensions',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'payment',
]

SITE_ID = 1
SOCIALACCOUNT_LOGIN_ON_GET = True
'''
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dbmih3try',
    'API_KEY': '284896676717458',
    'API_SECRET': 'q0C_5olnrIJMLjVk6MXB2oKkO58',
}'''

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'movidamo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'movidamo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'utenti.Utente'


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'it-IT'

TIME_ZONE = 'Europe/Rome'
USE_L10N = True
USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static/"),
)


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]


# Media settings
#DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.RawMediaCloudinaryStorage'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# CSRF Security
CSRF_COOKIE_SECURE = True
CSRF_TRUSTED_ORIGINS = ['https://movidamo.azurewebsites.net']

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    },
    'facebook': {
        'METHOD': 'oauth2',  
        'SDK_URL': '//connect.facebook.net/{locale}/sdk.js',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'first_name',
            'last_name',
            'middle_name',
            'name',
            'name_format',
            'picture',
            'short_name',
            'email',
        ],
        'EXCHANGE_TOKEN': True,
        'LOCALE_FUNC': 'path.to.callable',
        'VERIFIED_EMAIL': False,
        'VERSION': 'v13.0',
        'GRAPH_API_URL': 'https://graph.facebook.com/v13.0',
    }
}

LOGIN_REDIRECT_URL = '/'
SOCIALACCOUNT_ADAPTER = 'utenti.adapters.CustomUserSocialAccountAdapter'

STRIPE_TEST_PUBLIC_KEY= 'pk_test_51NxsW6Li8gs7fV7NjltMFSpOF4kuPfL8SNyl2UhGqXHshHTNwRztbDAVSEkC2Tm3dRHs58EqbEqNbPMvDc7wP0lz00WXh4W26b'
STRIPE_TEST_SECRET_KEY = 'sk_test_51NxsW6Li8gs7fV7Nhb1o1jC1HRENlyEdJTrzI33BaG1ekuh3Dsfk1CkphWFGIXulsbResKMR0Y4N9XQALoTpaUHf00h4Bo8AJ8'
STRIPE_SECRET_KEY = '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'
STRIPE_LINKED_ACCOUNTS_WEBHOOK_KEY = 'whsec_f84438ef11bb47df753262ae29c1fa68db4c666bab59dcc31f4e4d022fbe31ea'

TOKEN_SECRET_KEY = '_=l!!z(%1(-ohhc!$hh))avx1e+=^85&-x=v&-uqbxl47+x^*b'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'fracali99@gmail.com'
EMAIL_HOST_PASSWORD = 'frfk yyux kuzd shqo'
DEFAULT_FROM_EMAIL = 'fracali99@gmail.com'